default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123546
  timeout: 5000

development:
  <<: *default
  database: conecta
test:
  <<: *default
  database: conecta

production:
  <<: *default
  database: conecta